#@PURPOSE: Provide access to Chris Kohlhoff's ASIO library.
#
#@TARGETS:
#   ASIO::ASIO Chris Kohlhoff's ASIO library
#
#@DESCRIPTION: This module produces a single target 'ASIO::ASIO', that can be
# used to link to the asio library. The behavior of this module is undefined
# unless the asio library is in '../../asio' relative to this file.
#
# The 'asio' target generated by this module uses the "standalone" version of
# asio in that it doesn't depend on any Boost libraries.

# Try to find standalone ASIO (non-Boost)
# Provides: ASIO::ASIO

set(ASIO_FOUND FALSE)

if (TARGET ASIO::ASIO)
    set(ASIO_FOUND TRUE)
    return()
endif()

# --- Threads ---
find_package(Threads REQUIRED)

# --- Опції пошуку шляхів ---
set(_ASIO_SEARCH_PATHS
    "${CMAKE_CURRENT_LIST_DIR}/../../asio"                     # локальний поряд
    "${CMAKE_CURRENT_LIST_DIR}/../../asio/asio"                # підпапка
    "${CMAKE_SOURCE_DIR}/third_party/asio"
    "${CMAKE_SOURCE_DIR}/external/asio"
    "${CMAKE_SOURCE_DIR}/vendor/asio"
    "${CMAKE_SOURCE_DIR}/../asio"
    "$ENV{ASIO_ROOT}"
    "$ENV{VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}/include"
    "/usr/include"
    "C:/Program Files (x86)/asio"
)

# --- Знайти заголовок asio.hpp ---
find_path(ASIO_INCLUDE_DIR
    NAMES asio.hpp
    PATH_SUFFIXES asio
    PATHS ${_ASIO_SEARCH_PATHS}
    NO_DEFAULT_PATH
)

# Якщо не знайдено — спробувати ще раз із системними шляхами
if(NOT ASIO_INCLUDE_DIR)
    find_path(ASIO_INCLUDE_DIR
        NAMES asio.hpp
        PATH_SUFFIXES asio
    )
endif()

# --- Перевірка ---
if (ASIO_INCLUDE_DIR)
    add_library(ASIO::ASIO INTERFACE IMPORTED GLOBAL)
    set_target_properties(ASIO::ASIO PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${ASIO_INCLUDE_DIR}"
        INTERFACE_COMPILE_DEFINITIONS "ASIO_STANDALONE"
    )
    target_link_libraries(ASIO::ASIO INTERFACE Threads::Threads)

    set(ASIO_FOUND TRUE)
    message(STATUS "✅ Found ASIO in ${ASIO_INCLUDE_DIR}")
else()
    if (ASIO_FIND_REQUIRED)
        message(FATAL_ERROR "❌ ASIO headers could not be found.")
    else()
        message(WARNING "⚠️  ASIO headers not found. Set ASIO_ROOT or install via vcpkg.")
    endif()
endif()


# ----------------------------------------------------------------------------
# Copyright 2017 Bloomberg Finance L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
